name: Keep Alive
# Tries to keep the Render.com page alive by continuously pinging the health check URL every 5 minutes.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
  # Every 5 minutes.

jobs:
  ping_url:
    runs-on: ubuntu-latest
    name: Ping Health Check
    steps:
      - name: Check the URL
        id: ping
        uses: soul-wish/ping-url-javascript-action@v1.2
        with:
          url: 'https://haitouch.onrender.com/heartbeat'
